name: Build with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        distribution: [ 'adopt' ]
        java: [ '8', '11', '17' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.Java }} (${{ matrix.distribution }}) on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Install LibreOffice
        run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -y libreoffice
         elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install libreoffice-fresh
         elif [ "$RUNNER_OS" == "macOS" ]; then
              echo "MacOs install command"
              exit 1
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
        shell: bash
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: build
          
          
          
        
        

